service: mockytonk

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  environment:
    MOCKYTONK_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "*"
  tags:
    product: mockytonk

functions:
  proxy:
    handler: proxy.main
    memorySize: 128
    events:
      - http:
          path: proxy/{proxy+}
          method: any
  add-mock:
    handler: add_mock.main
    memorySize: 128
    events:
      - http:
          path: mock
          method: post
  remove-mock:
    handler: remove_mock.main
    memorySize: 128
    events:
      - http:
          path: mock/{id}/{secretKey}
          method: delete

resources:
  Resources:
    MockDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: sort
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: sort
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.MOCKYTONK_TABLE}
